# list of datasources to insert/update depending
# whats available in the database
apiVersion: 1

datasources:
  - name: InfluxDB-v2
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    version: 2
    editable: true
    default: true
    basicAuth: false
    jsonData:
      version: Flux
      organization: "projector_org"
      defaultBucket: "projector_bucket"

    secureJsonData:
      # If you want to specify your token securely, use this section instead of 'jsonData.token'
      token: "auth_token"
